FROM maven:3.9.9-eclipse-temurin-21-alpine

WORKDIR /app

COPY pom.xml ./

RUN mvn dependency:go-offline

EXPOSE 8080

CMD sh -c "mvn spring-boot:run -Dspring-boot.run.fork=false -Dspring-boot.run.jvmArguments='-Dspring.devtools.restart.enabled=true'"

docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management