services:
  postgres:
    image: 'postgres:17'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

  backend:
    build:
      context: ./profeco-back
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    volumes:
      - maven_cache:/root/.m2
      - ./profeco-back:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      # SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres


  frontend:
    build:
      context: ./profeco-front
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - ./profeco-front:/app
      - node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    depends_on:
      - backend

volumes:
  postgres_data:
  # postgres_data:
  maven_cache:
  node_modules: